# Basics of Data Cleaning

Dirty data can create problems in data analysis and has to be taken care of before proceeding to the next phase. This data consists of incorrect information. 

Sometimes in large datasets, completely removing dirty data from a source can be impossible so we aim to clean at least 80–90% of the data. To make good data predictions and create better visualizations with data, the raw data acquired must be cleaned because unclean data can impact data findings.

Data cleaning is a part of the data preprocessing stage. The replace function is the most common way to replace wrong values during data cleaning.
To do this we will create a dataframe with the different types of errors, identify them and fix them.

In [1]:
import numpy as np
import pandas as pd

## Create a dataframe of random people in 2022

In [2]:
#data entered by random people in 2022
df = pd.DataFrame({
    'Sex': ['F', 'F', 'M', 'M', 'M', 'M', 'D'],
    'Age': [15, 35, 23, 320, 32, 19, 28],
    'Name': ['Jane', 'Ada', 'Mark', 'John', 'John', 'Peter', 'Hope'],
    'Birth_Year': [2007, 1887, 1999, 1990, 1990, 2003, 1994],
    'Interests': ['Hiking', 'Travel', 'Sports', 'Books', 'Books', 'Swimming', 'Black'],
    'Favorite_Color': ['Blue', 'Purple', 'Green', 'White', 'White', np.nan, 'Movies']
})
df

Sex  Age   Name  Birth_Year Interests Favorite_Color
0   F   15   Jane        2007    Hiking           Blue
1   F   35    Ada        1887    Travel         Purple
2   M   23   Mark        1999    Sports          Green
3   M  320   John        1990     Books          White
4   M   32   John        1990     Books          White
5   M   19  Peter        2003  Swimming            NaN
6   D   28   Hope        1994     Black         Movies

### Bogus Data

This is the type of data you encounter in a variable that is not genuine or not true especially when the values are expected to follow a particular range. This data can happen due to a typing error. We can correct this data by replacing it with the actual value we estimate it to be or if it is private data, we can ask the owner to confirm the error. In the dataset, the bogus data is in the age column which age is 320. This is obviously a typing error so we change the age to 32.

In [3]:
df['Age'].unique()

array([ 15,  35,  23, 320,  32,  19,  28], dtype=int64)

In [4]:
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] / 10
df

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1887    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
4   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   D  28.0   Hope        1994     Black         Movies

### Duplicate Data

As the name implies, this data is encountered when data is entered twice. This can be solved by checking for duplicates in the dataframe and removing the duplicate values. In the dataframe, we see that the entry for John is duplicated so we remove one entry.

In [5]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool

In [6]:
df = df.drop_duplicates()
df

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1887    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   D  28.0   Hope        1994     Black         Movies

### Outdated Data

This type of data happens when we expect data from a particular period and we find values that are below or above the particular periods. We can check if the data was caused by a typing error by estimating if it falls in the range. But if the value is beyond the range, we can remove it from the dataset. In the dataframe, we see a birth year of 1887 and this data was generated from people in 2022. We calculate the actual year from the age and add the correct value.

In [7]:
df['Birth_Year'].unique()

array([2007, 1887, 1999, 1990, 2003, 1994], dtype=int64)

In [8]:
df.loc[df['Birth_Year'] == 1887, 'Birth_Year'] = df.loc[df['Birth_Year'] == 1887, 'Birth_Year'] + 100
df

C:\Users\Vanessa Onyema\anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1987    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   D  28.0   Hope        1994     Black         Movies

### Incorrect Data

Incorrect data is data entered in the wrong column. For example, when numerical data is entered in a text column or vice versa or when a value that should be in another column is entered in a different column. In the dataframe, black is entered in the interests column and movies is entered in the favorite color column so we replace these values.

In [9]:
df

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1987    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   D  28.0   Hope        1994     Black         Movies

In [10]:
df = df.replace({
    'Interests': {
        'Black': 'Movies'
    },
    'Favorite_Color': {
        'Movies': 'Black'
    }
})

In [11]:
df

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1987    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   D  28.0   Hope        1994    Movies          Black

### Inconsistent Data

This data is encountered when the data entered assumes the shape of a data but is not the same. This data is usually caused by a typing error. In the sex column, we see there is D entered and the alphabet D is close to F on the keyboard so we change this to F.

In [12]:

df['Sex'].unique()

array(['F', 'M', 'D'], dtype=object)

In [13]:
df = df.replace({
    'Sex': {
        'D': 'F'
    }})

In [14]:
df

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1987    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming            NaN
6   F  28.0   Hope        1994    Movies          Black

### Missing Data

This is a type of data that is returned as a null value. We can find the null values in the dataframe, remove them or replace them with an arbitrary value. There is a missing value in the favorite color column so we can change this to empty which indicates that it wasn't filled.

In [15]:
df.isnull()

Sex    Age   Name  Birth_Year  Interests  Favorite_Color
0  False  False  False       False      False           False
1  False  False  False       False      False           False
2  False  False  False       False      False           False
3  False  False  False       False      False           False
5  False  False  False       False      False            True
6  False  False  False       False      False           False

In [16]:
df.fillna('Empty')

Sex   Age   Name  Birth_Year Interests Favorite_Color
0   F  15.0   Jane        2007    Hiking           Blue
1   F  35.0    Ada        1987    Travel         Purple
2   M  23.0   Mark        1999    Sports          Green
3   M  32.0   John        1990     Books          White
5   M  19.0  Peter        2003  Swimming          Empty
6   F  28.0   Hope        1994    Movies          Black